title: ""
author: Raminder Singh
email: # Insert your email here (optional)
baseurl: ""
url: ""
description: >-
  A personal website.

# Optional socials
social_github: ramindersinghdubb
social_linkedin: raminder-singh-dubb



collections:
  projects:
    output: true
  posts:
    output: true
    permalink: /blog/:year/:month/:title



defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "project"
      smiling_face: false
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      smiling_face: false
  - scope:
      path: ""
    values:
      layout: "default"
      smiling_face: false